### ISSUE TITLE
Gene Expression e2e Tests Running Longer Due to Multiple Browser Testing

### ISSUE THREAD

**Issue by ashin-czi** [chanzuckerberg/single-cell-data-portal#4487] opened 2023-04-04 19:23 UTC
## Motivation

Changes from the team helping out with e2e testing Gene Expression has introduced a feature to test across three different browsers (chrome, firefox, edge)

As of writing this, the testing for each browser is being done sequentially
chrome -> firefox -> edge

This ticket is to investigate parallelizing the browser tests so each browser is being run asynchronously.

This might be a playwright config that needs to be set

## Definition of Done

e2e tests should run around the same duration as testing one browser.

## Tasks

- [ ] Reach out to testing team to see if tests can be configured to run asynchronously for browsers

**Comment by tihuan** [comment] 2023-04-04 19:31
Thanks for catching this! Is this happening locally or GH Actions? Thank you!

Cc: @charles-testco

**Comment by tihuan** [comment] 2023-04-05 21:59
@charles-testco is addressing this ticket via: #4488 thank you!

**Comment by dsadgat** [comment] 2023-04-19 19:46
@tihuan @ashin-czi Is this ticket closeable?

**Comment by tihuan** [comment] 2023-04-20 21:07
I think this ticket feels like a duplicate of #4488, so maybe we can close this one and just use #4488 going forward!

**Closed by tihuan** 2023-04-20 21:07 UTC
Labels: tech, testing, gene expression, data-viz
