### ISSUE TITLE
reinstate TestAuthorizer tests as functional tests

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#1936] opened 2022-02-08 14:35 UTC
The `unit.backend.api.common.test_authorizer.TestAuthorizer` tests do not run currently locally or in GHA, since they are skipped when run inside a Docker container:
```
@unittest.skipIf(os.getenv("IS_DOCKER_DEV"), "No access to auth0 in docker")
```

Note these tests rely upon making a real calls to Auth0.

Suggested changes:
* Move the test class into the _functional_ test directory, so that it only runs during deploy-time dev/staging/prod-env testing.
* The `backend.api.data_portal.common.authorizer.assert_authorized_token()` method is part of the code path being exercised, and this method contains code for test-env specific behavior. If possible, we should remove that special-case logic.
* If any parts of `authorizer.py` can be truly unit tested (e.g. by using a test fixture for the auth token, and not relying upon real secret config values and live auth0 call), such tests should be extracted or created.
* Rename "corpora/cicd/test/auth0-secret" to "corpora/backend/cicd-test/auth0-secret", since I think that's a bit clearer and the "backend" path is more consistent with the normal `corpora/backend/<env>/auth0-secret` secret path. At a minimum this special AWS secret should be better documented (e.g., in README, affected class files, setup_dev_data.sh, etc.)
* Remove `IS_DOCKER_DEV` env throughout code base (defined in `docker-compose.yml` and used in `test_authorizer.py`). The env var name on its own does not convey it's intent, and we don't seem to need it anyway after reworking these tests.

**Comment by atolopko-czi** [comment] 2022-12-07 23:59
@Bento007 is this worth doing?

**Comment by metakuni** [comment] 2023-10-27 22:54
Closing since `TestAuthorizer` no longer exists and there are no `@unittest.skipIf(os.getenv("IS_DOCKER_DEV")`.

Confirmed with @Bento007 .

**Closed by metakuni** 2023-10-27 22:54 UTC
Labels: backend, tech, testing, dp
