### ISSUE TITLE
Revision publication permitted without any changes

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#4223] opened 2023-02-16 18:10 UTC
To reproduce: 

- publish a Collection
- start a revision
- note that `Publish` button is grayed out given that no changes have been made
- select option `Edit Details` (Collection metadata) but do not make any changes; click `Save`, NOT `cancel`
- `Publish` button is no longer grayed out; Collection can be published; a new Collection version is instantiated on the backend even though no changes were made to the Collection (whether metadata or Datasets).

**Comment by brianraymor** [comment] 2023-03-01 22:47
This is an edge case in the Curator UX. Prior to the refactor, this would not have been a problem because `revised_at` is not updated for changes limited to collection metadata. Now, it would result in a false positive for a new collection version. 

I'm also unsure whether this is a regression. Currently, all validation occurs on the front-end, so this should be detected to short-circuit the API call if no changes occurred.

**Comment by brianraymor** [comment] 2023-06-21 17:24
Triaging with @metakuni - closing because this is an extreme edge case and has no known serious impact. CC: @jahilton

**Closed by brianraymor** 2023-06-21 17:24 UTC
Labels: frontend, bug, P2, curation ux, dp
