### ISSUE TITLE
Selecting a cell type and then a disease that doesn't have that cell type results in a page crash

### ISSUE THREAD

**Issue by joyceyan** [chanzuckerberg/single-cell-data-portal#5779] opened 2023-09-15 16:31 UTC
Steps to reproduce for "Disease" filter:
1. Select cell type "B Cell" and "Bergmann glial cell"
2. Select "influenza" as the disease
3. Page should crash

**Comment by joyceyan** [comment] 2023-09-15 16:34
Implementing the fix for this can probably be consolidated with https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5777

It's also likely we'll have a similar issue with all of the secondary filters

**Comment by signechambers1** [comment] 2023-10-30 17:58
Closing, cannot reproduce in prod as of 10/30. I think this was fixed in #5777

**Closed by signechambers1** 2023-10-30 17:58 UTC
Labels: bug, P1, gene expression, data-viz
