### ISSUE TITLE
Add cleanup to the functional revision test

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#1791] opened 2021-12-22 20:34 UTC
Now that public collections can be deleted, we should add a cleanup mechanism so that the functional revision test will not leave zombie collections. A few notes:

1. A cleanup mechanism already exists in Python (see the other functional test - `test_api.py`). No need for anything manual.
1. Make sure that the cleanup works when the test fails as well
1. Deleting a public collection likely requires curator permissions, so we should enable the test account used by the functional tests, and make sure that the cleanup process uses the right token.

**Comment by maniarathi** [comment] 2022-07-05 13:49
Closing as a duplicate of #1375

**Closed by maniarathi** 2022-07-05 13:49 UTC
