### ISSUE TITLE
Comma separated list of genes does not clear when you hit "Clear Genes"

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#5780] opened 2023-09-15 16:33 UTC
Steps to reproduce:
1. Prod
2. Add comma separated list of genes to Add Genes entry box: CFTR,SFTPB,SFTPC,ABCA3,CSF2RA,CSF2RB,COPA,LRBA,STAT3,MUC5B
3. Application loads correctly
4. Click "Clear Genes"
5. Dot plot clears genes but gene entry box still has list of genes in it

Desired result: Add Gene box is also empty

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTZtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1fcf37e68512081c236daa44ba94b08954b3f629/Screenshot%202023-09-15%20at%209.29.58%20AM.png)

**Comment by seve** [comment] 2023-09-19 22:31
should we clear the entry box on "enter" button press?

**Comment by karenliang0** [comment] 2023-09-25 22:43
Yes, we should clear entry box on "enter" button press for the gene
dropdown!

**Comment by joyceyan** [comment] 2023-10-16 19:15
Closing this out since we can't reproduce the issue anymore. It was likely inadvertently fixed by work we did on another ticket.

**Closed by joyceyan** 2023-10-16 19:15 UTC
Labels: bug, P2, data-viz
