### ISSUE TITLE
Update dependencies 

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell-data-portal#1212] opened 2021-06-01 21:17 UTC
## Need
Update the dependencies in all repos as described in [pr in single-cell repo](https://github.com/chanzuckerberg/single-cell/pull/173)

Whoever does this issue, please note to other team members (maybe in eng channel) of any issues that you ran into and approximately how long it took so that we can better predict in the future.

**Comment by MDunitz** [comment] 2021-06-15 19:35
Pin tiledb to .08 or update to 0.9 and fix failing tests. See https://czi-sci.slack.com/archives/C013K0JB8F8/p1623783813001500?thread_ts=1617855347.006400&cid=C013K0JB8F8

**Comment by maniarathi** [comment] 2021-06-19 16:38
Failing tests fixed in #2249.

**Comment by maniarathi** [comment] 2021-06-19 16:39
Oops -- incorrectly closed this issue. This is to update all the requirements, not just tiledb.

**Comment by MDunitz** [comment] 2021-06-22 17:27
After updating deploy both the explorer and the data portal to the staging env and hack around to check for incompatibilities

**Comment by maniarathi** [comment] 2022-07-29 01:51
Closing as duplicate of other dependency upgrade issues.

**Closed by maniarathi** 2022-07-29 01:51 UTC
Labels: backend
