### ISSUE TITLE
Portal deployed_version endpoint not reporting version

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#4311] opened 2023-03-07 22:53 UTC
## Motivation

Cannot easily verify the deployed version due to endpoint not working:

https://api.cellxgene.cziscience.com/dp/v1/deployed_version responded:
```
{
"Data Portal": ""
}
```

## Definition of Done

Endpoint reports the deployed version

## Tasks

- [ ] Troubleshoot and fix

**Comment by seve** [comment] 2023-04-03 17:50
Wasn't able to get this done during my on-call. I added a test to check that the deployed_version !== "" and that was passing when running `make local-unit-test`. So this may be only occurring when the containers are built for deployment?

**Comment by dsadgat** [comment] 2023-04-19 19:57
@ebezzi was there progress made on this ticket?

**Comment by ebezzi** [comment] 2023-04-19 20:30
Yes, I did some more investigation, but wasn't able to understand the cause of the flakyness. I isolated the issue and the problem is at build time (if the endpoint returns empty, it means the Docker container was built with an empty variable). It is not clear to me yet what causes the Docker container to be built with the empty variable - likely a happy issue. I probably need to add some logs to the build pipeline and see if they add clarity. I am _happy_ to assign the ticket to me and keep working/monitoring while we do deployments.

**Comment by metakuni** [comment] 2023-07-11 21:42
This appears to be working now:

```
// 20230711143942
// https://api.cellxgene.cziscience.com/dp/v1/deployed_version

{
  "Data Portal": "21d07e9a9e78c881b42bdbe27cd5f7c90a04e07f"
}
```

but leaving this issue open until we figure out the root cause.

**Comment by metakuni** [comment] 2023-07-11 21:47
Case in point re: flakiness:

Staging is also working:
```
// 20230711144248
// https://api.cellxgene.staging.single-cell.czi.technology/dp/v1/deployed_version

{
  "Data Portal": "3646a4c30f74149da4e1d3bca8de35d20e60519f"
}
```

but not dev:
```
// 20230711144246
// https://api.cellxgene.dev.single-cell.czi.technology/dp/v1/deployed_version

{
  "Data Portal": ""
}
```

Preassigning to @ebezzi for further investigation on his next on-call rotation.

**Comment by metakuni** [comment] 2023-08-24 23:02
I think this can be closed in favor of #5479 .

cc: @atolopko-czi , @Bento007

**Comment by metakuni** [comment] 2023-08-24 23:09
Assigning to @Bento007 for consideration

**Comment by atolopko-czi** [comment] 2023-08-25 12:38
If we're giving up on trying to fix this, I would recommend this issue be changed to _remove_ the flakey endpoint.

**Comment by metakuni** [comment] 2023-08-25 18:13
Removing from CI/CD and addressing as on-call work.

**Closed** 2023-10-12 16:01 UTC
Labels: P1, tech, on-call, dp
