### ISSUE TITLE
Add Discover API 'datasets/<id>/versions' endpoint to fetch all versions of a particular dataset

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4263] opened 2023-02-27 17:33 UTC
Endpoint should return an array of dataset version metadata. 

Only allow fetching using a canonical ID.

Update OpenAPI spec accordingly.

**Comment by brianraymor** [comment] 2023-03-10 03:06
@nayib-jose-gloria @danieljhegeman - closing as duplicate of [Implement: `/dataset_versions/{dataset_version_id}`](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4326).

**Closed by brianraymor** 2023-03-10 03:06 UTC
