### ISSUE TITLE
Modal spins, does not close when deleting a Dataset

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#4071] opened 2023-01-27 09:10 UTC
Fairly simple-to-describe bug: when attempting to delete a Dataset from a Collection, the 'confirm delete' modal spins endlessly after clicking Delete. It does not close. Upon refreshing, the Collection shows that the Dataset has been deleted. A console error indicates an error in JSON processing of the response returned presumably from the delete API call.

DoD
- Delete modal closes within a reasonably time frame after clicking 'Delete' (or 'cancel' for that matter). 
- The Collection presents with the Dataset deleted successfully
- The Dataset has indeed been (marked as) deleted in the database.

**Comment by ebezzi** [comment] 2023-02-01 17:23
According to a preliminary investigation, the FE is expecting a JSON response from the delete dataset endpoint, which isn't returned. The response isn't documented in Swagger either, so we have two options:
1. Add a FE-conforming JSON response to the endpoint (likely will need to contain the id, or be empty - need to check the js code) and add it to the swagger
2. Change the FE so that the response is ignored.

**Comment by metakuni** [comment] 2023-02-06 05:23
@ebezzi : Will you still be working on this?

**Comment by danieljhegeman** [comment] 2023-02-06 05:38
I am happy to tackle this later, as a backlog item, unless @ebezzi has spare cycles while I'm busy with initial API refinement work

**Comment by atolopko-czi** [comment] 2023-02-07 14:11
I'm removing tech label, since this is a product-specific defect and the on-call engineer is not expected for to tackle this.

**Comment by brianraymor** [comment] 2023-06-02 00:53
Closing since we're removing the UX to delete published datasets in a revision - see #3037. 

In addition, I could not reproduce on Dev. I deleted a published dataset and then deleted a new dataset.

**Closed by brianraymor** 2023-06-02 00:53 UTC
Labels: bug, P1, curation ux
