### ISSUE TITLE
The download dataset UX must detect and warn about unavailable Seurat downloads

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1598] opened 2021-10-27 21:16 UTC
#### Context

See conversations on [**ux**](https://czi-sci.slack.com/archives/C02450L5YAX/p1635211104016200) and [**ingestion**](https://czi-sci.slack.com/archives/C02JP4SALNQ/p1635184609017000). 

Also - [Seurat Failure Investigations](https://docs.google.com/document/d/1AHN3Jkz3mb3T1F-Tr3h3cTrKotE6Ls2SPHg3wB5ppiI/edit#heading=h.ukkfc1tjv8r1). 

---
#### Design

If the portal API does **not** return a `dataset_assets` element with a `filetype": "RDS"`, this indicates that the dataset could not be converted to Seurat during ingestion. Similar to [Disable exploration of datasets larger than 2 million cells](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1538), the experience for the download modal should be:

1. Disable the `rds (Seurat v3)` choice
2. Include hover text for this choice with a warning "A .rds (Seurat v3) download is unavailable due to limitations in the R dgCMatrix sparse matrix class."

This must be implemented for _A Collection_ in the following cases:

1. Private collections
2. Public collections
3. Private revisions of public collections

--- 

#### UX

[Figma](https://www.figma.com/file/jZzZF9oO0YRMxmVRDxDHp3/Public-Revisions?node-id=1346%3A30497)

**Comment by danieljhegeman** [comment] 2021-12-01 09:32
@brianraymor is there any need to present a warning to the user _upon initial creation/upload of the dataset_ that rds will not be available? I thought there had been discussion of this but I might be misremembering. cc @seve

**Comment by brianraymor** [comment] 2021-12-01 16:30
The user upon initial creation/upload of the dataset is the curator. They must validate using the `cellxgene-schema` CLI prior to upload, so the CLI has already warned them. They should also be reviewing the downloads, so they're warned again about the lack of the RDS conversion based on this issue.

**Comment by danieljhegeman** [comment] 2021-12-01 21:00
Ok, sounds good

**Comment by brianraymor** [comment] 2021-12-17 22:53
@seve - re-opened. The hover text is not displaying in production for this [collection](https://cellxgene.cziscience.com/collections/af893e86-8e9f-41f1-a474-ef05359b1fb7) and its _All major cell types in adult human retina_ dataset:

https://images.zenhubusercontent.com/228681195/ada12502-ad77-4d2a-84cc-885e10cfb0b6/screen_recording_2021_12_17_at_2_50_42_pm.mov

**Comment by seve** [comment] 2021-12-21 22:22
This may be due to the dataset artifacts being generated and processed before we introduced the SKIPPED state.  I'm seeing the following for the processing status:
```
      "processing_status": {
        "created_at": 1635377711.91238,
        "cxg_status": "UPLOADED",
        "dataset_id": "aad97cb5-f375-45ef-ae9d-178e7f5d5180",
        "h5ad_status": "UPLOADED",
        "id": "96309620-cfd8-479e-8481-0043ee3472da",
        "processing_status": "SUCCESS",
        "rds_status": "CONVERTED",
        "updated_at": 1640057553.261527,
        "upload_progress": 1,
        "upload_status": "UPLOADED",
        "validation_status": "VALID"
      },
```

Is there a way we can reprocess these assets, or are we going to have to code a special case collections like this? 

cc: @danieljhegeman

**Comment by danieljhegeman** [comment] 2021-12-21 22:26
@seve yeah so I noticed this with a few datasets and made brief mention of it during the demo: what you said is correct, we will be missing the hover-over text for datasets that were processed before we introduced the SKIPPED state. 

However, @metakuni recently announced that he finished reprocessing all datasets. So one would think this would have been resolved by now. I will chat with him, or he can respond here...

**Comment by danieljhegeman** [comment] 2021-12-21 22:26
@seve in response to special case: no, we just need to reprocess everything, but again, see above

**Comment by seve** [comment] 2021-12-21 22:26
Created at: 
```GMT: Wednesday, October 27, 2021 11:35:11.912 PM```

**Comment by seve** [comment] 2021-12-21 22:29
Speedy response ⚡ 

I think I can verify, the updated timestamp on processing status is:
```
Your time zone: Monday, December 20, 2021 7:32:33.261 PM GMT-08:00
```

Interesting, is this a backend bug and not frontend?

**Comment by danieljhegeman** [comment] 2021-12-21 22:32
Ok I don't know the specifics of how @metakuni reprocessed things, maybe there was special scripting. Could be a backend bug inherent to the prod code. Will check.

**Comment by brianraymor** [comment] 2021-12-21 22:59
@seve - why simply check the dataset_assets for a filetype of "RDS"?

**Comment by seve** [comment] 2021-12-21 23:07
> @seve - why not simply check the dataset_assets for a filetype of "RDS"?

I believe these two conversations address that

https://github.com/chanzuckerberg/single-cell-data-portal/pull/1694#discussion_r760000964

https://github.com/chanzuckerberg/single-cell-data-portal/pull/1694#discussion_r760001504

**Comment by danieljhegeman** [comment] 2021-12-21 23:08
> why not simply check the dataset_assets for a filetype of "RDS"?

@brianraymor I assume you mean using absence of .rds filetype to indicate the FE should gray-out the .rds radio button and display hover text. I briefly discussed the equivalent issue with @seve back when we were making the initial changes but we wanted to make these changes specifically for the case in which the .rds is not available because of the R array size issue (for which the hover text is specific).

**Comment by seve** [comment] 2021-12-21 23:12
> edit: fyi @seve those links aren't taking me to the actual conversation... just the initial PR... also I'm not even seeing those conversations on that PR! Did they get removed due to fresh commits rendering old code obsolete...?

Maybe because the conversations are resolved? You should be able to expand them:
![image](https://user-images.githubusercontent.com/8716829/147009493-1a650133-eeb1-4bc5-93aa-804a31f42c53.png)

**Comment by danieljhegeman** [comment] 2021-12-21 23:18
![Screen Shot 2021-12-21 at 3 17 54 PM](https://user-images.githubusercontent.com/23110111/147009963-bf7dc7a4-ecec-4a9f-a46e-764aafc41e42.png)

**Comment by brianraymor** [comment] 2021-12-21 23:30
> but we wanted to make these changes specifically for the case in which the .rds is not available because of the R array size issue

What other case is there? The only time that the RDS download "should be" unavailable is when conversion is skipped. If conversion fails, then that's a bug.

**Comment by metakuni** [comment] 2021-12-22 15:14
> I think I can verify, the updated timestamp on processing status is:
> 
> ```
> Your time zone: Monday, December 20, 2021 7:32:33.261 PM GMT-08:00
> ```

Yup, correct. As part of the Seurat reconversions, the `updated_at` was updated to indicate the reconversion time.

**Comment by danieljhegeman** [comment] 2021-12-23 01:07
Here's a summary of the situation:

- @metakuni 's reprocessing of all of the seurat-convertible files did not serve the function of updating the `rds_status` for datasets that couldn't be converted to seurat, which were not marked as `SKIPPED` at the time, because he didn't reprocess those files. Which is fine.
- @brianraymor has said that any dataset which does not have a dataset artifact of `filetype` = `RDS` was necessarily skipped because of the specific seurat conversion problem, i.e. it is safe to update the conversion status `rds_status` to `SKIPPED` for any such datasets.
-We can manually apply this update to postgres for any dataset that was created before the 'skipped' status was introduced to prod (which occurred about a month ago I believe). This is easier than changing the existing FE code to render the hover text for all datasets which lack an rds artifact.

**Comment by danieljhegeman** [comment] 2021-12-23 01:34
This gives us all extant (`tombstone = false`) datasets which do not have an rds artifact associated with them:

`select distinct d.id, d.created_at, d.updated_at, dps.rds_status from dataset as d join dataset_artifact as da on d.id = da.dataset_id join dataset_processing_status as dps on d.id = dps.dataset_id where d.tombstone = false and d.id not in (select distinct d.id from dataset as d join dataset_artifact as da on d.id = da.dataset_id where d.tombstone = false and da.filetype = 'RDS');`

`                  id                  |         created_at         |         updated_at         | rds_status 
--------------------------------------+----------------------------+----------------------------+------------
 0129dbd9-a7d3-4f6b-96b9-1da155a93748 | 2021-11-18 00:10:23.637519 | 2021-11-18 19:40:27.181061 | 
 1fa42e4b-91be-46bf-8d89-5b52dff790bb | 2021-03-30 21:47:49.174116 | 2021-09-14 20:44:23.63864  | FAILED
 218acb0f-9f2f-4f76-b90b-15a4b7c7f629 | 2021-11-17 22:29:01.347208 | 2021-11-19 20:09:35.878046 | 
 34b5a4fc-eaf5-4fb5-80a2-8d0f53407840 | 2021-03-30 21:38:39.472697 | 2021-03-30 21:53:33.151002 | CONVERTING
 56bb6916-2914-49e3-9be2-65c37456fdb7 | 2021-03-30 21:47:23.709739 | 2021-09-14 20:44:23.63883  | FAILED
 8aeb48d6-328e-4680-81f0-799bce86a3f4 | 2021-03-30 21:47:30.163777 | 2021-09-14 20:44:23.638982 | FAILED
 aa9430ca-ee95-41b7-9c79-580fcf0aaeab | 2021-03-30 21:50:00.201679 | 2021-09-14 20:44:23.639077 | FAILED
`

**Comment by brianraymor** [comment] 2021-12-23 02:03
@metakuni @danieljhegeman 

You need to ensure that [Delete previous Seurat artifacts for revised datasets that would fail conversion](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1580) is addressed. 

Despite the earlier [comment](https://github.com/chanzuckerberg/single-cell-data-portal/issues/1580#issuecomment-988311038), these custom RDS .tar files are still available for download and their `rds_status` is `"CONVERTED"`.  


For example:


       "collection_id": "e5f58829-1a66-40b5-a624-9046778e74f5",
        "collection_visibility": "PUBLIC",
        "created_at": 1626721600.225782,
        "dataset_assets": [
          {
            "created_at": 1633120665.572364,
            "dataset_id": "53d208b0-2cfd-4366-9866-c3c6114081bc",
            "filename": "local.tar",
            "filetype": "RDS",
            "id": "c7ea84e3-f873-4316-bbfd-fdf8af12eb3a",
            "s3_uri": "s3://corpora-data-prod/bd964147-a970-49e9-be4d-c3abad7b240a/local.tar",
            "type": "REMIX",
            "updated_at": 1633717895.904972,
            "user_submitted": true
          },

        "processing_status": {
          "created_at": 1626721600.242224,
          "cxg_status": "CONVERTED",
          "dataset_id": "53d208b0-2cfd-4366-9866-c3c6114081bc",
          "h5ad_status": "CONVERTED",
          "id": "487080c9-774c-4a1f-81b4-a3203506980f",
          "processing_status": "SUCCESS",
          "rds_status": "CONVERTED",
          "updated_at": 1626729256.889855,
          "upload_progress": 1.0,
          "upload_status": "UPLOADED",
          "v

**Comment by brianraymor** [comment] 2021-12-23 02:04
And I disagree with simply changing the `rds_status` to `"SKIPPED"` and leaving the .tar file in place because it requires API developers to then check the rds_status to determine whether to download the asset that's still available.

**Comment by danieljhegeman** [comment] 2021-12-23 02:54
@brianraymor I think we're talking about two slightly different issues. But yes, #1580 is being addressed and will be merged shortly (to make sure we delete obsolete/out-of-date seurat).

The (different) problem I was addressing above is as follows: there are 7 datasets which do not have a rds-type dataset artifact associated with them but are also _not_ marked as `SKIPPED`; the dataset you referenced earlier today as not displaying the hover text for the grayed-out seurat download radio button is one of them. For all 7 of these datasets, there is *neither* 1) an associated rds-type `dataset_artifact` in postgres, nor 2) an `.rds` file in that dataset's s3 bucket. Therefore I believe the statuses can (should) be marked as `SKIPPED`.

Let me know if you think I've misinterpreted 😅

**Comment by danieljhegeman** [comment] 2021-12-23 03:10
Or, perhaps better: we reprocess those 7 datasets.

If we can produce seurat, great; if we can't, the status will be updated to `SKIPPED` (will need to trigger in a different fashion than Kuni's paradigm). And there are no rds artifacts so we can do it before merging #1580.

**Comment by brianraymor** [comment] 2021-12-23 05:43
For **public** collections, I see 2 datasets that do not include RDS and 5 datasets that have custom tar files. I also didn't see the dataset id for my example in your list? 

I think it would be helpful to document collection id and dataset id for the set that are in question.

**Comment by danieljhegeman** [comment] 2021-12-23 09:47
I think I might be lacking some important understanding about "bespoke seurat", which I'm gathering equates (roughly? exactly?) to "custom tar files".

If a `dataset` does _not_ have a `dataset_artifact` with `filetype = 'RDS'`, does this mean it does not have an associated rds file, bespoke or otherwise? Or is a bespoke seurat/custom tar file entity represented in our database in some fashion other than with a row in `dataset_artifact` where `filetype = 'RDS'`?

**Comment by danieljhegeman** [comment] 2021-12-23 09:54
> For public collections, I see 2 datasets that do not include RDS and 5 datasets that have custom tar files. I also didn't see the dataset id for my example in your list?

In the list of 7 datasets that I posted, the first dataset is the one you were referencing for this issue originally: `0129dbd9-a7d3-4f6b-96b9-1da155a93748`.

I checked on the `collection_visibility` for each of the 7 datasets I listed, and the breakdown is also 5 private / 2 public; I'm assuming there must be something I'm missing about where to find / access these 'custom tar files' associated with the 5 private datasets. 😰

**Comment by brianraymor** [comment] 2021-12-23 16:30
The five datasets that I referenced are **public**, not private. See the example that I shared above -  their `filename` is `"local.tar"` and their 'filetype' is `"RDS"`. 

If we were changing any private collections, I would want to review with Stanford for awareness.

**Comment by danieljhegeman** [comment] 2021-12-24 06:40
ok, got it, misinterpreted your previous message. Either way I think we're still talking past each other slightly. The query I mentioned running earlier was to find all datasets that lack an associated rds artifact (whether regular or custom)--every such dataset should be updated to have a `dataset_processing_status.rds_status = 'SKIPPED'`. I found 7 such datasets: 2 public, one of which is the dataset you mentioned a couple days ago here:

> @seve - re-opened. The hover text is not displaying in production for this collection and its All major cell types in adult human retina dataset:

And the other 5 are private. I acknowledge these are not the same datasets as the 5 public ones you mention. But I am still a little unclear on what your concern with those 5 public datasets is. Are you saying that these datasets specifically are ones that you know need to have the existing rds artifact deleted?

**Comment by metakuni** [comment] 2022-01-03 19:31
As discussed at today's planning meeting, since Seve is on PTO until next week, reassigned to Dan.

**Comment by danieljhegeman** [comment] 2022-01-03 22:52
Fixed by manually changing `dataset_processing_status.rds_status` to `SKIPPED` for all 7 datasets which did not have an rds artifact associated with them (whether in `dataset_artifact` and/or in s3). The datasets:

```0129dbd9-a7d3-4f6b-96b9-1da155a93748
 1fa42e4b-91be-46bf-8d89-5b52dff790bb
 218acb0f-9f2f-4f76-b90b-15a4b7c7f629
 34b5a4fc-eaf5-4fb5-80a2-8d0f53407840
 56bb6916-2914-49e3-9be2-65c37456fdb7
 8aeb48d6-328e-4680-81f0-799bce86a3f4
 aa9430ca-ee95-41b7-9c79-580fcf0aaeab```

**Comment by danieljhegeman** [comment] 2022-01-18 22:12
@brianraymor the one thing @seve and I didn't foresee is pipeline error resulting in `UPLOADED` as status for h5ad, rds, and cxg. The overall `dataset_processing_status` is `SUCCESS` while the individual file statuses were never closed out correctly (as either `CONVERTED` or `SKIPPED`).

```corpora_staging=> select rds_status, cxg_status, h5ad_status, processing_status from dataset_processing_status where dataset_id = '462d7e2f-dec2-42ca-81e0-61d1af5b2b06';
 rds_status | cxg_status | h5ad_status | processing_status 
------------+------------+-------------+-------------------
 UPLOADED   | UPLOADED   | UPLOADED    | SUCCESS
```

**Comment by brianraymor** [comment] 2022-01-18 23:11
Still think it's simpler to show the hover when the RDS file is unavailable ... it would have been _done and dusted_.

**Comment by danieljhegeman** [comment] 2022-01-28 08:40
Confirmed toast is appearing for Datasets in staging where the seurat artifact is not available (even if status is UPLOADING or CONVERTING).

**Closed** 2022-02-02 19:20 UTC
Labels: frontend
