### ISSUE TITLE
Generate FE and compute script curated ontology constants from a single source

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#6278] opened 2023-11-28 18:06 UTC
#### Need
Currently, when the set of curated tissues or cell types is updated, the corresponding FE constants (e.g. [cell type cell class](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/frontend/src/components/common/Filter/common/constants.ts#L275), [cell type cell subclass](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/frontend/src/components/common/Filter/common/constants.ts#L321), [tissue system](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/frontend/src/components/common/Filter/common/constants.ts#L572), [tissue organ](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/frontend/src/components/common/Filter/common/constants.ts#L451)) and compute script constants (e.g. [cell type cell class](https://github.com/chanzuckerberg/single-cell-curation/blob/main/scripts/compute_mappings/compute_tissue_and_cell_type_mappings.py#L221), [cell type cell subclass](https://github.com/chanzuckerberg/single-cell-curation/blob/main/scripts/compute_mappings/compute_tissue_and_cell_type_mappings.py#L238), [tissue system](https://github.com/chanzuckerberg/single-cell-curation/blob/main/scripts/compute_mappings/compute_tissue_and_cell_type_mappings.py#L126), [tissue organ](https://github.com/chanzuckerberg/single-cell-curation/blob/main/scripts/compute_mappings/compute_tissue_and_cell_type_mappings.py#L151)) must manually be updated. All constants should be generated from a single source of truth. 

See [tissue_descendants_json](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/frontend/src/components/common/Filter/common/constants.ts#L15) as an example of a FE constant generated by the compute script.

**Comment by nayib-jose-gloria** [comment] 2024-03-14 17:22
dupe of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/cellxgene-ontology-guide/103

**Closed by nayib-jose-gloria** 2024-03-14 17:22 UTC
