### ISSUE TITLE
fix(wmg): add cell type term id to the request body of the filters endpoint for celltype filter in WMGv2

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#5489] opened 2023-08-14 20:14 UTC
## Environment

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by signechambers1** [comment] 2023-09-08 16:23
Closing as a duplicate of #5716

**Closed by signechambers1** 2023-09-08 16:23 UTC
Labels: bug, gene expression, data-viz
