### ISSUE TITLE
Wrong error message displayed for conversion failure

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1019] opened 2021-03-25 21:09 UTC
UPDATED DEFINITION OF DONE
- [ ] Remove the "please try again" error. Only show the error that we'll investigate on our end.
- [ ] Update the lambda so that we don't override the upload status upon batch process failure.

----- OLDER TICKET DETAILS -----

@pablo-gar [reported a loom conversion failure](https://chanzuckerbergteam.slack.com/archives/C01CPJURT0S/p1616618497032100) but the error message indicated an upload failure and suggested a retry in the related screen snapshot:

![image.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/1d29d0c8-d2d2-4a81-83a2-db29ec419a7a)

rather than the [conversion error message](https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Publisher-Collection?node-id=0%3A1).

Here's the job
https://us-west-2.console.aws.amazon.com/batch/v2/home?region=us-west-2#jobs/detail/7a164232-552c-4933-a136-b2c72c85c9ea

```
OSError: Driver write request failed (file write failed: time = Wed Mar 24 20:00:45 2021, filename = 'local.loom', file descriptor = 5, errno = 28, error message = 'No space left on device', buf = 0x1e2f5090, total write size = 1700, bytes this sub-write = 1700,
```

**Comment by maniarathi** [comment] 2021-04-06 21:19
Can this be moved to Ready for QA?

**Comment by brianraymor** [comment] 2021-04-14 00:42
How do we know that this has been addressed?

**Comment by Bento007** [comment] 2021-04-16 19:18
So the problem was fixed with running out of storage space to create the loom file. You will need to upload larger datasets to reproduce this bug. 

As far as the error message, what should we tell the user when their dataset fails because of our backend infra failing?

**Comment by brianraymor** [comment] 2021-04-16 20:42
The appropriate message is:
```

 The dataset was uploaded successfully, but one or more conversions from
        .h5ad failed. We&apos;ll attempt to fix this manually and follow-up in
        an email after we&apos;ve investigated. 
```

**Comment by Bento007** [comment] 2021-04-16 23:17
In the backend download code under certain conditions we set the upload_status=FAILED, but don’t stop the container from processing([Fix on the way](https://github.com/chanzuckerberg/corpora-data-portal/pull/1105)). So the container was downloading when it ran out of space. This caused us to set upload_status=FAILED and continue processing.  The other conversions failed due to a lack of space. The frontend code read the status and return the correct error message since the upload did in fact fail. The logs said OSerror for the loom and cxg because they tried to create files on an already full container.

We don’t have the original processing_status to confirm that this is what happened for the original upload, but we have increased the logging to catch it in the future. The other mystery is why didn’t validation fail if we only had a partially downloaded H5AD.

I’ll fix the issue with the downloader not stopping execution on failure which should prevent these confusing errors from happening again. I’ll also not set upload_status=FAILED for OSError, since those are most like because of something with the container.

The fronted returned the expected error and the logs were misinterpreted. In the future, the frontend will return the error “There was an unexpected problem. Please try again.” if this happens again.

**Comment by Bento007** [comment] 2021-04-16 23:24
Here is an updated link to the original failing batch job https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/$252Fdp$252Fprod$252Fprodstack$252Fupload/log-events/dp-prod-prodstack-upload$252Fdefault$252F6bc7900b154d45fd9ed886546fe1a5b9

**Comment by tihuan** [comment] 2021-08-13 16:57
@MDunitz will add bad dataset from PR here! Thanks!

**Comment by MDunitz** [comment] 2021-08-13 18:05
@brianraymor you should be able to test with this dataset https://www.dropbox.com/s/ccnukp6ehra5vei/dead_small_dataset.h5ad?dl=0

**Comment by brianraymor** [comment] 2021-08-13 18:30
It fails as expected @MDunitz.

@hthomas-czi is this the message text that you prefer? 

<img width="297" alt="Screen Shot 2021-08-13 at 11 23 35 AM" src="https://user-images.githubusercontent.com/3644743/129402905-8c9dadc4-947e-43e6-ad77-9eaedf1ebd0f.png">

Reviewing the original Figma(s), the original was - https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Publisher-Collection?node-id=492%3A184 ?

**Comment by hthomas-czi** [comment] 2021-08-13 20:03
@brianraymor @MDunitz The text doesn't need to match the Figma exactly but it'd be good to give the user as much information as we can about:

1. What error occurred
2. What they can do about it

**Comment by brianraymor** [comment] 2021-08-13 20:20
For conversion errors, there's no action that a curator can immediately take. We should inform them about "what happens next?". 

@maniarathi and @maesen - do you have guidance about what Dev is willing to promise operationally? For example:

_The conversion for _Fill-in-the-blank_ failed. No further action is required on your part at this time. The cellxgene team is reviewing and will contact you only if we require information to resolve the issue._

It's unclear whether we want to offer any SLA(s) such as _within N hours_.  My concern about the ambiguity of the current message is that there will be at least one curator who will attempt the upload once or twice more before pinging their favorite CZI curator in confusion and/or frustration.

**Comment by tihuan** [comment] 2021-08-16 16:50
@maniarathi might reuse the existing error will follow up offline!

**Comment by tihuan** [comment] 2021-08-30 16:51
The new error message has removed the "try again part", which meets the requirement

@brianraymor will create a new ticket for a better error message!

**Comment by tihuan** [comment] 2021-08-30 16:52
@tihuan check if deployed to prod

**Closed** 2021-09-24 16:36 UTC
Labels: bug
