### ISSUE TITLE
Selecting a cell on one organism type and then switching organism type results in a page crash

### ISSUE THREAD

**Issue by joyceyan** [chanzuckerberg/single-cell-data-portal#5777] opened 2023-09-15 16:26 UTC
Steps to reproduce:
1. Make sure "homo sapiens" is selected as the organism type
2. Select B-1A B cell in the cell filter
3. Switch the organism type to "mus musculus"
3. Page should crash

Desired outcome:
1. Keep Organism selection bar where it is currently
2. If a user has any genes or filters selected, changing to a different organism will prompt a confirmation dialog.
3. If confirmed, page should reset to default page with all filters and settings reset

[Figma Designs](https://www.figma.com/file/z6CczUpCBQUuIHGq826hzN/2023-H2-Gene-Expression-Improvements?type=design&node-id=128%3A11493&mode=design&t=JxNm0YFrEFuX5N8L-1)
[Prototype](https://www.figma.com/proto/z6CczUpCBQUuIHGq826hzN/2023-H2-Gene-Expression-Improvements?page-id=88%3A36606&type=design&node-id=114-45325&viewport=109%2C972%2C0.22&t=BRQBVFitKNUupik1-1&scaling=min-zoom&starting-point-node-id=114%3A45325&mode=design)

**Comment by signechambers1** [comment] 2023-09-15 16:40
@signechambers1 to propose a flow for switching organism when cell type filter is used cc @karenliang0

**Comment by signechambers1** [comment] 2023-09-27 17:39
Options from @karenliang0: 
1. Disable the ability to select the other organism with a hover over explanation as to why it's disabled
2. Or allow users to change to the other organism and the cell type filter that affects it will clear itself
we can also add a dialog that has them confirm the organism switch if there are cell types that will not be available in the organism they're switching to

I think the organism filter is a little misleading - it is more of a setting since genes and cell types don't transfer across organism (though filters do). If we go with optoin #1, when would organism filter be enabled?

**Comment by signechambers1** [comment] 2023-10-12 17:25
Discussed with @karenliang0, we aligned on desired outcome listed in the ticket.

**Comment by tihuan** [comment] 2023-10-18 15:10
Morning @karenliang0 !

I just moved the Organism selector to the top. Does the spacing look good?

Thank you!

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzlMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--257203fa031fd78b56184b2e25eecc2fc4fe11b4/Screenshot%202023-10-18%20at%208.08.03%E2%80%AFAM.png)

**Comment by signechambers1** [comment] 2023-10-18 17:01
@karenliang0 curious what you think but I would put the organism selector above the filters header.

**Comment by tihuan** [comment] 2023-10-18 17:18
Yeah I thought about that either! But if we move the "Filters" header below organism selector, do we need another header in the Filters header's current place or just leave it blank?

**Comment by tihuan** [comment] 2023-10-18 21:58
https://github.com/chanzuckerberg/single-cell-data-portal/issues/5778 is a duplicate of this!

I think we can close #5777 and Seve's fix can still get merged, but keep #5778 open, so we can address the UI change

CC: @seve

**Comment by tihuan** [comment] 2023-10-18 22:22
Putting this back to disorder until design is finalized

**Comment by karenliang0** [comment] 2023-10-20 16:42
@tihuan @signechambers1 

Adjusted outcomes and added final designs and link to the prototype. 
@tihuan sorry for the back and forth, we'll be keeping the organism selector where we previously had it (below filters but above the rest of the items in the panel). We're adding a confirmation dialog to inform folks that all genes and filters will be cleared if they try to change organism when they currently have any filters / genes selected. If they do not have anything selected, we will allow them to switch organism without a confirmation dialog prompt. 

Let me know if there are any questions - more than happy to walk you through it in a call! Just let me know if that would be more helpful :)

**Comment by signechambers1** [comment] 2023-10-25 20:38
@tihuan looks good except the spacing between tissues after you switch the organism is off - i think @seve fixed this in a separate PR. Otherwise LGTM![Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkp4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ef815ba17b0be486e7f53b8f02edcf595410600/Screenshot%202023-10-25%20at%201.37.41%20PM.png)

**Comment by tihuan** [comment] 2023-10-25 20:44
Awesome thanks so much, Signe! Yeah that should be addressed in https://github.com/chanzuckerberg/single-cell-data-portal/pull/5938 👍 

Thank you!

**Comment by karenliang0** [comment] 2023-10-25 21:20
Looks great, Timmy! Thanks so much 👏

**Comment by tihuan** [comment] 2023-10-25 21:46
Hurray! Thanks for the swift review, @karenliang0 !! ❤️

**Closed** 2023-11-02 19:51 UTC
Labels: bug, P1, gene expression, data-viz
