### ISSUE TITLE
bug(authentication): 500 returned with jwt shaped token

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#4359] opened 2023-03-16 23:20 UTC
## Describe the bug
If a JWT shaped token is used to authenticate in the discover API, a 500 is returned when hitting secured endpoints.

```
{
    "levelname": "ERROR",
    "asctime": "2023-03-16T22:11:50.016Z",
    "name": "corpora-api-rdev",
    "message": "InternalServerError",
    "lineno": 182,
    "pathname": "/single-cell-data-portal/backend/api_server/app.py",
    "request_id": "d9ba9a9b-621a-42b6-8805-f1c118958ae3",
    "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/flask/app.py\", line 1823, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python3.10/dist-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File \"/usr/local/lib/python3.10/dist-packages/connexion/decorators/decorator.py\", line 68, in wrapper\n    response = function(request)\n  File \"/usr/local/lib/python3.10/dist-packages/connexion/security/security_handler_factory.py\", line 380, in wrapper\n    cls._raise_most_specific(errors)\n  File \"/usr/local/lib/python3.10/dist-packages/connexion/security/security_handler_factory.py\", line 421, in _raise_most_specific\n    raise status_to_exc[lowest_status_code]\n  File \"/usr/local/lib/python3.10/dist-packages/connexion/security/security_handler_factory.py\", line 372, in wrapper\n    token_info = func(request)\n  File \"/usr/local/lib/python3.10/dist-packages/connexion/security/security_handler_factory.py\", line 270, in wrapper\n    return check_bearer_func(request, token)\n  File \"/usr/local/lib/python3.10/dist-packages/connexion/security/security_handler_factory.py\", line 322, in wrapper\n    token_info = func(*args, **kwargs)\n  File \"/single-cell-data-portal/backend/portal/api/app/v1/authentication.py\", line 201, in curation_access_token_func\n    return assert_authorized_token(token, CorporaAuthConfig().curation_audience)\n  File \"/single-cell-data-portal/backend/common/authorizer.py\", line 37, in assert_authorized_token\n    public_key = public_keys.get(unverified_header[\"kid\"])\nKeyError: 'kid'"
}
```

## To Reproduce

Generate an API key and use it as in the auth header sent to the discover API.

example curl:
```
curl -X 'POST' \
  'https://large-dataset-backend.rdev.single-cell.czi.technology/curation/v1/auth/token' \
  -H 'accept: application/json' \
  -H 'x-api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODQxOTIzMjguMTM4ODY2NCwiaWF0IjoxNjc5MDA4MzI4LjEzODg2NjQsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTEzODg0MDgwMjMwNDUzNTEwMjg5In0.9hmgsEXsg4Vfr-0kr1Q_HpOUpNL7ayBiwWR6s9a5S20' \
  -d ''
```
The API key used is no longer active.

## Expected behavior

A 403 should be returned if the key is invalid in any way.

## Environment

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by brianraymor** [comment] 2023-06-21 16:37
@Bento007 - @metakuni and I are triaging for H2. Is this case for expired API keys? It's unclear from reading the description. Can you advise?

**Comment by brianraymor** [comment] 2023-06-21 18:24
I care about expiration because I do not want curators to become confused about the cause. What is the current TTL for an API key?

What is the scenario for a _key with missing fields_? DP generates the key.

**Comment by Bento007** [comment] 2023-06-21 19:10
> What is the scenario for a key with missing fields? DP generates the key.
This would most likely be a bad actor doing things they shouldn't.  It shouldn't happen with regular use.

> I care about expiration because I do not want curators to become confused about the cause. What is the current TTL for an API key?
The current TTL is 60 day. We raise a 401 error expire credential are detected and include a message that indicated the credentials are expired.

**Comment by brianraymor** [comment] 2023-06-21 20:01
@Bento007 - Thanks for the additional information. 

If this case is only for _bad actors_, then I'm fine returning a 500 rather than providing a more detailed error response. 

I'd recommending closing this issue. CC: @metakuni.

**Closed** 2023-06-21 23:24 UTC
Labels: bug, discover api, dp
