### ISSUE TITLE
feat(wmg): Remove bad marker genes and limit to top 25

### ISSUE THREAD

**Issue by ashin-czi** [chanzuckerberg/single-cell-data-portal#4240] opened 2023-02-21 21:29 UTC
Continuation of #4087 

We will be removing bad marker genes (>1) and limit marker genes shown to only the top 25

We will also be displaying in the FMG panel if there are not any reliable genes to be shown

[figma](https://www.figma.com/file/blyEMZDsi7EMopyyIX4XAg/Q1-2023-Gene-Expression-Improvements?node-id=376%3A437490&t=hU9Hmz8Vwpa9aBQv-1)

**Comment by ashin-czi** [comment] 2023-02-22 17:15
@ainfeld If we're still doing the analytics for empty marker genes, can you update this ticket with the analytic event name?

**Comment by ashin-czi** [comment] 2023-02-22 17:33
@karenliang0 if we're filtering out the <1 genes, then should we also remove the `Low: <1` in the panel?

**Comment by signechambers1** [comment] 2023-02-22 18:24
@ashin-czi we're only removing marker genes less than 0.5. I'm going to close this ticket as a duplicate of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4228

**Closed by signechambers1** 2023-02-22 18:24 UTC
Labels: P0, gene expression
