### ISSUE TITLE
Add Discover API 'datasets index' endpoint

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4262] opened 2023-02-27 17:21 UTC
Similar to the Discover API’s Collections index endpoint, the response will comprise of the most recently published version of all Datasets. Response shape should include dataset preview metadata response + all data from dataset's 'datasets/<id>/assets' endpoint response.

Update curation-api OpenAPI spec accordingly

**Comment by brianraymor** [comment] 2023-03-10 03:00
@nayib-jose-gloria @danieljhegeman - closing as duplicate of [Implement: `/datasets` index endpoint](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4324).

**Closed** 2023-03-10 03:02 UTC
