### ISSUE TITLE
Fix test_api_key_crud flakey test

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#5420] opened 2023-08-08 14:38 UTC
Assess/fix flakey test `test_api_key_crud` (tests.functional.backend.corpora.test_api_key.TestApiKey) [GHA job](https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/5790908562/job/15694927052). Retry passed.

**Comment by metakuni** [comment] 2023-11-15 01:39
GHA has since deleted the [job run noted in the description](https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/5790908562/job/15694927052), but looks like `test_api_key_crud` is still flakey. It failed 4 times over the past week in stage [sic]:
* https://github.com/chanzuckerberg/single-cell-data-portal/actions/workflows/deploy-happy-stack.yml

**Comment by metakuni** [comment] 2023-11-17 23:23
Closing this issue as a duplicate of #6198 since it includes more info.

**Closed by metakuni** 2023-11-17 23:23 UTC
Labels: bug, P1, tech, testing, on-call, dp
