### ISSUE TITLE
Delete previous Seurat artifacts for revised datasets that would fail conversion

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-data-portal#1580] opened 2021-10-26 18:31 UTC
Consider the following two cases during revision of public collections:

In the published collection, the dataset was successfully converted to seurat. If a curator updates the dataset in a revision and it would fail seurat conversion, then the original seurat artifact MUST be deleted when the revision is **published**.

In the published collection, the seurat conversion failed and a bespoke conversion was manually created (and perhaps stored in a .tar file).  If a curator updates the dataset in a revision and it would fail seurat conversion, then the original seurat artifact MUST be deleted when the revision is **published**.

**Comment by metakuni** [comment] 2021-11-29 18:27
Reassigning to Dan so that Emanuele can work on #1584 which blocks #1582.

**Comment by danieljhegeman** [comment] 2021-12-07 22:35
@maniarathi made the astute observation that we don't actually need to delete .rds rows in the `dataset` table because they're only relevant insofar as they can be downloaded via the UI, and since we're about to reprocess all files after the uns metadata update, all files that can't be converted to seurat (or which have bespoke versions) will be updated with a `SKIPPED` status, which means any lingering seurat datasets will not actually be downloadable via the UI (since the .rds radio button will be disabled). cc @metakuni

**Comment by brianraymor** [comment] 2021-12-23 02:00
> which means any lingering seurat datasets will not actually be downloadable via the UI (since the .rds radio button will be disabled).

@danieljhegeman - but you still need to consider downloads via the API.  It's more complex to tell developers - don't download an existing RDS file IF the processing state for RDS is "SKIPPED".

**Comment by danieljhegeman** [comment] 2021-12-23 02:15
Yes this ticket is being addressed and will be merged once I make the update to the unit test.

**Comment by danieljhegeman** [comment] 2022-01-18 22:09
Confirmed in staging

**Closed** 2022-01-28 08:41 UTC
Labels: backend
